// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var ReactDom = require("react-dom");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");
var Styles = require("@material-ui/core/styles");

var theme = Styles.createTheme({});

var closeButtonOriginal = React.createElement("button", {
      className: "close",
      type: "button"
    }, React.createElement("i", {
          className: "fa fa-close"
        }));

var closeButton = React.cloneElement(closeButtonOriginal, {
      "data-toggle": "tooltip",
      title: "Close wizard",
      "data-placement": "left"
    });

function Test$Wizard(Props) {
  var match = React.useState(function () {
        return {
                page: /* Start_page */0
              };
      });
  var setState = match[1];
  var onClick = function (evt) {
    evt.preventDefault();
    return Curry._1(setState, (function (param) {
                  return {
                          page: /* Survey_title */1
                        };
                }));
  };
  var match$1 = match[0].page;
  var page = match$1 ? React.createElement("form", undefined, React.createElement("div", {
              className: "form-group"
            }, React.createElement("label", undefined, "Survey title:"), React.createElement("input", {
                  className: "form-control",
                  type: "text"
                })), React.createElement("a", {
              className: "previous"
            }, "Previous"), React.createElement("button", {
              className: "btn btn-default next",
              onClick: onClick
            }, "Next")) : React.createElement("div", undefined, React.createElement("p", {
              className: "introduction"
            }, "Hi! \xf0\x9f\x91\x8b"), React.createElement("p", {
              className: "introduction"
            }, "Welcome to the LimeSurvey Wizard, that will guide you through the basics of survey creation."));
  return React.createElement("div", {
              className: "text-center",
              id: "wizard-root"
            }, React.createElement("h1", {
                  id: "wizard-header"
                }, "LimeSurvey Wizard"), closeButton, React.createElement("div", {
                  id: "wizard-inputs"
                }, page));
}

var Wizard = {
  variant: "text",
  className: "btn btn-default",
  theme: theme,
  closeButtonOriginal: closeButtonOriginal,
  closeButton: closeButton,
  make: Test$Wizard
};

console.log("Mooo?");

var NoRoot = /* @__PURE__ */Caml_exceptions.create("Test.NoRoot");

var root = document.querySelector("#root");

if (root == null) {
  throw {
        RE_EXN_ID: NoRoot,
        Error: new Error()
      };
}

ReactDom.render(React.createElement(Test$Wizard, {}), root);

exports.Wizard = Wizard;
exports.NoRoot = NoRoot;
/* theme Not a pure module */
